#!/bin/bash

# Define Interfaces
WG_INTERFACE="term7.wireguard"

# Define Config Files
WG_RULES="/home/admin/script/nftables/wireguard.conf"
DEFAULT_RULES="/etc/nftables.conf"
UNBOUND_CONFIG="/etc/unbound/unbound.conf.d/local-zones.conf"

# Define WireGuard DNS Config
WG_DNS_CONFIG="# Upstream DNS via WireGuard\nforward-zone:\n    name: \".\"\n    forward-addr: 10.13.0.1"

case "$1" in
    $WG_INTERFACE)
        case "$2" in
            up)
                # Apply WireGuard firewall rules
                /usr/sbin/nft -f "$WG_RULES"

                # Append WireGuard DNS to Unbound if not already present
                if ! grep -Fxq "$WG_DNS_CONFIG" "$UNBOUND_CONFIG"; then
                    echo -e "\n$WG_DNS_CONFIG" | sudo tee -a "$UNBOUND_CONFIG" > /dev/null
                fi

                sudo systemctl restart unbound
                sudo systemctl restart fail2ban
                ;;
            down)
                # Restore default nftables rules
                /usr/sbin/nft -f "$DEFAULT_RULES"

                # Remove WireGuard DNS Config
                sed -i '/fallback-enabled: yes/,$d' "$UNBOUND_CONFIG"
                echo "        fallback-enabled: yes" | sudo tee -a "$UNBOUND_CONFIG" > /dev/null

                sudo systemctl restart unbound
                sudo systemctl restart fail2ban
                ;;
        esac
        ;;
esac